from pathlib import Path
import json

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams


# ============================================================
# CONFIGURATION
# ============================================================

INPUT_PATH = Path("data/embeddings.json")

QDRANT_PATH = Path("data/qdrant")

COLLECTION_NAME = "rag_documents"

VECTOR_SIZE = 384

DISTANCE_METRIC = Distance.COSINE

# If True, an existing collection will be removed and
# recreated. Keep False during normal runs.
RECREATE_COLLECTION = False


# ============================================================
# LOAD EMBEDDINGS
# ============================================================

def load_embeddings() -> dict:
    """
    Load the embeddings generated by create_embeddings.py.
    """

    if not INPUT_PATH.exists():
        raise FileNotFoundError(
            f"Embeddings file not found: {INPUT_PATH}"
        )

    with open(
        INPUT_PATH,
        "r",
        encoding="utf-8"
    ) as file:
        data = json.load(file)

    if "metadata" not in data:
        raise ValueError(
            "Invalid embeddings.json: "
            "metadata section missing."
        )

    if "embeddings" not in data:
        raise ValueError(
            "Invalid embeddings.json: "
            "embeddings section missing."
        )

    if not data["embeddings"]:
        raise ValueError(
            "embeddings.json contains no embeddings."
        )

    return data


# ============================================================
# VALIDATE EMBEDDINGS
# ============================================================

def validate_embeddings(data: dict) -> None:
    """
    Verify that the embeddings match our expected
    vector configuration.
    """

    metadata = data["metadata"]
    embeddings = data["embeddings"]

    # --------------------------------------------------------
    # Check model dimension
    # --------------------------------------------------------

    stored_dimension = metadata.get("dimension")

    if stored_dimension != VECTOR_SIZE:
        raise ValueError(
            f"Vector dimension mismatch. "
            f"Expected {VECTOR_SIZE}, "
            f"got {stored_dimension}."
        )

    # --------------------------------------------------------
    # Check every vector
    # --------------------------------------------------------

    for index, item in enumerate(embeddings, start=1):

        if "embedding" not in item:
            raise ValueError(
                f"Embedding missing for item {index}."
            )

        vector = item["embedding"]

        if len(vector) != VECTOR_SIZE:
            raise ValueError(
                f"Invalid vector size at item {index}. "
                f"Expected {VECTOR_SIZE}, "
                f"got {len(vector)}."
            )

    print("Embedding validation: PASSED")
    print(
        f"Verified {len(embeddings):,} "
        f"vectors × {VECTOR_SIZE} dimensions."
    )


# ============================================================
# CONNECT TO LOCAL QDRANT
# ============================================================

def create_client() -> QdrantClient:
    """
    Create a persistent local Qdrant client.

    No server or cloud account is required.
    """

    QDRANT_PATH.mkdir(
        parents=True,
        exist_ok=True
    )

    print(
        f"Opening local Qdrant database: "
        f"{QDRANT_PATH}"
    )

    client = QdrantClient(
        path=str(QDRANT_PATH)
    )

    return client


# ============================================================
# CREATE COLLECTION
# ============================================================

def setup_collection(
    client: QdrantClient
) -> None:
    """
    Create the Qdrant collection if it does not exist.
    """

    collection_exists = client.collection_exists(
        collection_name=COLLECTION_NAME
    )

    # --------------------------------------------------------
    # Recreate if explicitly requested
    # --------------------------------------------------------

    if collection_exists and RECREATE_COLLECTION:

        print(
            f"Collection '{COLLECTION_NAME}' "
            f"already exists."
        )

        print("Recreating collection...")

        client.delete_collection(
            collection_name=COLLECTION_NAME
        )

        collection_exists = False

    # --------------------------------------------------------
    # Create collection
    # --------------------------------------------------------

    if not collection_exists:

        print(
            f"Creating collection: "
            f"{COLLECTION_NAME}"
        )

        client.create_collection(
            collection_name=COLLECTION_NAME,
            vectors_config=VectorParams(
                size=VECTOR_SIZE,
                distance=DISTANCE_METRIC
            )
        )

        print("Collection created successfully.")

    else:

        print(
            f"Collection '{COLLECTION_NAME}' "
            f"already exists."
        )


# ============================================================
# COLLECTION INFORMATION
# ============================================================

def print_collection_info(
    client: QdrantClient
) -> None:

    info = client.get_collection(
        collection_name=COLLECTION_NAME
    )

    print("\nQdrant Collection")
    print("-----------------")

    print(
        f"Name:             "
        f"{COLLECTION_NAME}"
    )

    print(
        f"Vector size:      "
        f"{info.config.params.vectors.size}"
    )

    print(
        f"Distance:         "
        f"{info.config.params.vectors.distance}"
    )

    print(
        f"Points currently: "
        f"{info.points_count}"
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print("Starting Qdrant setup...\n")

    # --------------------------------------------------------
    # Load embeddings
    # --------------------------------------------------------

    data = load_embeddings()

    embeddings = data["embeddings"]

    print(
        f"Loaded {len(embeddings):,} "
        f"embedded chunks."
    )

    # --------------------------------------------------------
    # Validate
    # --------------------------------------------------------

    validate_embeddings(data)

    # --------------------------------------------------------
    # Create local client
    # --------------------------------------------------------

    client = create_client()

    # --------------------------------------------------------
    # Create collection
    # --------------------------------------------------------

    setup_collection(client)

    # --------------------------------------------------------
    # Show final information
    # --------------------------------------------------------

    print_collection_info(client)

    print("\nQdrant setup completed successfully.")


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()